//Expense items types
export const GET_EXPENSE_ITEMS = 'GET_EXPENSE_ITEMS';
export const ADD_EXPENSE_ITEM = 'ADD_EXPENSE_ITEM';
export const DELETE_EXPENSE_ITEM = 'DELETE_EXPENSE_ITEM';
export const EXPENSE_ITEMS_LOADING = 'EXPENSE_ITEMS_LOADING';
export const EDIT_EXPENSE_ITEM = 'EDIT_EXPENSE_ITEM';
export const GET_EXPENSE_AMOUNT_ITEMS = 'GET_EXPENSE_AMOUNT_ITEMS';

//Income items types
export const GET_INCOME_ITEMS = 'GET_INCOME_ITEMS';
export const ADD_INCOME_ITEM = 'ADD_INCOME_ITEM';
export const DELETE_INCOME_ITEM = 'DELETE_INCOME_ITEM';
export const INCOME_ITEMS_LOADING = 'INCOME_ITEMS_LOADING';
export const EDIT_INCOME_ITEM = 'EDIT_INCOME_ITEM';
